package vista;

import controlador.AdminController;
import controlador.ProgresoController;
import controlador.BitacoraManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class AdminView extends javax.swing.JFrame {

    private AdminController adminController;
    private ProgresoController progresoController;
    private BitacoraManager bitacoraManager;

    public AdminView(AdminController adminController, ProgresoController progresoController, BitacoraManager bitacoraManager) {
        this.adminController = adminController;
        this.progresoController = progresoController;
        this.bitacoraManager = bitacoraManager;

        initComponentes();
    }

    private void initComponentes() {
        setTitle("Administrador - Taller Automotriz");
        setSize(600, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new GridLayout(4, 2, 10, 10));

        JLabel saludo = new JLabel("Bienvenido Administrador", SwingConstants.CENTER);
        saludo.setFont(new Font("Arial", Font.BOLD, 16));
        add(saludo);

        JButton btnClientes = new JButton("Gestionar Clientes");
        JButton btnRepuestos = new JButton("Gestionar Repuestos");
        JButton btnServicios = new JButton("Gestionar Servicios");
        JButton btnProgreso = new JButton("Ver Progreso");
        JButton btnBitacora = new JButton("Ver Bitácora");
        JButton btnSalir = new JButton("Cerrar Sesión");

        btnClientes.addActionListener(e -> JOptionPane.showMessageDialog(this, "Función Clientes aún no implementada."));
        btnRepuestos.addActionListener(e -> JOptionPane.showMessageDialog(this, "Función Repuestos aún no implementada."));
        btnServicios.addActionListener(e -> JOptionPane.showMessageDialog(this, "Función Servicios aún no implementada."));
        btnProgreso.addActionListener(e -> JOptionPane.showMessageDialog(this, "Función Progreso aún no implementada."));
        btnBitacora.addActionListener(e -> JOptionPane.showMessageDialog(this, "Función Bitácora aún no implementada."));
        btnSalir.addActionListener(e -> {
            this.dispose();
            new LoginView(adminController, progresoController, bitacoraManager).setVisible(true);
        });

        add(btnClientes);
        add(btnRepuestos);
        add(btnServicios);
        add(btnProgreso);
        add(btnBitacora);
        add(btnSalir);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminController adminController = new AdminController();
                ProgresoController progresoController = new ProgresoController();
                BitacoraManager bitacoraManager = new BitacoraManager();

                new AdminView(adminController, progresoController, bitacoraManager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
